{% set version = "0.16.0" %}

package:
  name: hatch-mypyc
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/h/hatch-mypyc/hatch_mypyc-{{ version }}.tar.gz
  sha256: 6e3aa99634d81142cab993358698eaae823de91fe87ee85029a82f2e737c3ded
  patches:
    - 0000-test-as-installed.patch

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - hatchling >=1.12.2
    - pip
    - python {{ python_min }}
  run:
    - hatchling >=1.12.2
    - mypy >=0.971
    - mypyc
    - pathspec
    - python >={{ python_min }}
    - setuptools

test:
  source_files:
    - tests
  imports:
    - hatch_mypyc
  requires:
    - packaging
    - pip
    - pytest-cov
    - pytest-mock
    - python-build
    - tomli
    - virtualenv >=20.0.35
    - python {{ python_min }}
  commands:
    - pip check
    - pytest -vv --cov hatch_mypyc --cov ./tests --cov-branch --cov-report=term-missing:skip-covered --no-cov-on-fail --cov-fail-under=90

about:
  home: https://pypi.org/project/hatch-mypyc
  summary: Hatch build hook plugin for Mypyc
  dev_url: https://github.com/ofek/hatch-mypyc
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - bollwyvl
