{% set version = "0.15.0" %}

package:
  name: hatch-mypyc
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/h/hatch-mypyc/hatch_mypyc-{{ version }}.tar.gz
  sha256: bda7c00b859ea163ce7a2f4f4ffe37c0932b28a4bf19806f40000678f9598eda
  patches:
    - 0000-test-as-installed.patch

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - hatchling >=1.12.2
    - pip
    - python >=3.7
  run:
    - hatchling >=1.12.2
    - mypy >=0.971,<1.dev0
    - mypyc
    - packaging !=22.0
    - pathspec
    - python >=3.7
    - setuptools

test:
  source_files:
    - tests
  imports:
    - hatch_mypyc
  requires:
    - packaging
    - pip
    - pytest-cov
    - pytest-mock
    - python-build
    - tomli
    - virtualenv >=20.0.35
  commands:
    - pip check
    - pytest -vv --cov hatch_mypyc --cov ./tests --cov-branch --cov-report=term-missing:skip-covered --no-cov-on-fail --cov-fail-under=90

about:
  home: https://pypi.org/project/hatch-mypyc
  summary: Hatch build hook plugin for Mypyc
  dev_url: https://github.com/ofek/hatch-mypyc
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - bollwyvl
